# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\rcommunication\"\xad\x01\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61ttery\x18\x05 \x01(\x01\x12\x10\n\x08kickLoad\x18\x06 \x01(\x01\x12\x0e\n\x06irBall\x18\x07 \x01(\x08\x12\'\n\x08velocity\x18\x08 \x01(\x0b\x32\x15.communication.Motors\x12&\n\x07\x63urrent\x18\t \x01(\x0b\x32\x15.communication.Motors\x12\x11\n\ttimestamp\x18\n \x01(\x04\"8\n\x06Motors\x12\n\n\x02m1\x18\x01 \x01(\x01\x12\n\n\x02m2\x18\x02 \x01(\x01\x12\n\n\x02m3\x18\x03 \x01(\x01\x12\n\n\x02m4\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEEDBACK._serialized_start=39
  _FEEDBACK._serialized_end=212
  _MOTORS._serialized_start=214
  _MOTORS._serialized_end=270
# @@protoc_insertion_point(module_scope)
